### ISSUE TITLE
cookie[i].session 总是false，导致未登录上传不了图片

### ISSUE THREAD

**Issue by h-dj** [HeMOua/cnblogsUpload#4]
环境： deepin 15.11 

```
 if((cookie[i].name == '.Cnblogs.AspNetCore.Cookies' || cookie[i].name == '.CNBlogsCookie') && cookie[i].session)
```
打印了日志，发现cookie[i].session 总是为false，但Cookie一个带截至日期的持久 cookie。最后我去掉这个条件才能上传，请问为什么要判断这个cookie[i].session 条件呢？

**Comment by HeMOua** [comment]
因为只有登录成功时才会有 `.Cnblogs.AspNetCore.Cookies` 这个cookie，当时可能想多了。现在去掉了一些判断条件，能正常上传了。
